### ISSUE TITLE
[feature request] aggiungere separatori tra i diversi grafici

### ISSUE THREAD

**Issue by azrafe7** [amadvance/covid19-italy#1]
Ottimo lavoro, complimenti davvero!

La mia richiesta/idea è quella di rendere più chiara la separazione di un grafico (e relativa descrizione) dal successivo. Magari con dei "sopra" o "sotto"-titoli, o semplicemente aumentando lo spazio tra figure e testo.

**Comment by amadvance** [comment]
Grazie! 

Ho aggiunto un po' di spazio, e inditcato nel testo che si tratta del grafico successivo.
